REFRESH_INTERVAL = 300  # seconds

INDICES = {
    # Broad market
    "Nifty 50":          "^NSEI",
    "Nifty Next 50":     "NEXT50.NS",
    "Nifty 100":         "^CNX100",
    "Nifty 200":         "^CNX200",
    # Mid & Small cap
    "Nifty Midcap 50":   "^NSEMDCP50",
    "Nifty Midcap 150":  "NIFTYMIDCAP150.NS",
    # Sectoral
    "Nifty Bank":        "^NSEBANK",
    "Nifty IT":          "^CNXIT",
    "Nifty Auto":        "^CNXAUTO",
    "Nifty FMCG":        "^CNXFMCG",
    "Nifty Pharma":      "^CNXPHARMA",
    "Nifty Metal":       "^CNXMETAL",
    "Nifty Realty":      "^CNXREALTY",
    "Nifty Energy":      "^CNXENERGY",
    "Nifty PSU Bank":    "^CNXPSUBANK",
    "Nifty Fin Service": "NIFTY_FIN_SERVICE.NS",
    "Nifty Infra":       "^CNXINFRA",
    "Nifty Media":       "^CNXMEDIA",
    "Nifty CPSE":        "^CNXPSE",
    "Nifty MNC":         "^CNXMNC",
}

SECTOR_STOCKS = {
    "Nifty 50": [
        ("Reliance", "RELIANCE.NS"), ("TCS", "TCS.NS"), ("HDFC Bank", "HDFCBANK.NS"),
        ("ICICI Bank", "ICICIBANK.NS"), ("Infosys", "INFY.NS"), ("Bharti Airtel", "BHARTIARTL.NS"),
        ("SBI", "SBIN.NS"), ("L&T", "LT.NS"), ("HUL", "HINDUNILVR.NS"), ("ITC", "ITC.NS"),
        ("Kotak Bank", "KOTAKBANK.NS"), ("Axis Bank", "AXISBANK.NS"), ("HCL Tech", "HCLTECH.NS"),
        ("Wipro", "WIPRO.NS"), ("Bajaj Finance", "BAJFINANCE.NS"), ("Maruti", "MARUTI.NS"),
        ("Titan", "TITAN.NS"), ("Sun Pharma", "SUNPHARMA.NS"), ("NTPC", "NTPC.NS"),
        ("Power Grid", "POWERGRID.NS"), ("Tata Motors", "TATAMOTORS.NS"), ("M&M", "M&M.NS"),
        ("Tech Mahindra", "TECHM.NS"), ("UltraCemco", "ULTRACEMCO.NS"), ("ONGC", "ONGC.NS"),
        ("Coal India", "COALINDIA.NS"), ("Nestle", "NESTLEIND.NS"), ("Tata Steel", "TATASTEEL.NS"),
        ("JSW Steel", "JSWSTEEL.NS"), ("HAL", "HAL.NS"), ("Adani Ports", "ADANIPORTS.NS"),
        ("Dr Reddy's", "DRREDDY.NS"), ("Cipla", "CIPLA.NS"), ("Bajaj Auto", "BAJAJ-AUTO.NS"),
        ("Eicher Motors", "EICHERMOT.NS"), ("Hero MotoCorp", "HEROMOTOCO.NS"),
        ("Hindalco", "HINDALCO.NS"), ("BPCL", "BPCL.NS"), ("Tata Consumer", "TATACONSUM.NS"),
        ("IndusInd Bank", "INDUSINDBK.NS"), ("Grasim", "GRASIM.NS"), ("Divis Lab", "DIVISLAB.NS"),
        ("Britannia", "BRITANNIA.NS"), ("Apollo Hospitals", "APOLLOHOSP.NS"),
        ("SBI Life", "SBILIFE.NS"), ("HDFC Life", "HDFCLIFE.NS"), ("LTIMindtree", "LTIM.NS"),
        ("Shriram Finance", "SHRIRAMFIN.NS"), ("BEL", "BEL.NS"), ("Adani Ent.", "ADANIENT.NS"),
    ],
    "Nifty Next 50": [
        ("Adani Green", "ADANIGREEN.NS"), ("Adani Total Gas", "ATGL.NS"), ("Ambuja Cements", "AMBUJACEM.NS"),
        ("Astral", "ASTRAL.NS"), ("Avenue Supermarts", "DMART.NS"), ("Berger Paints", "BERGEPAINT.NS"),
        ("Bosch", "BOSCHLTD.NS"), ("Canara Bank", "CANBK.NS"), ("Cholamandalam", "CHOLAFIN.NS"),
        ("Colgate", "COLPAL.NS"), ("Cummins India", "CUMMINSIND.NS"), ("DLF", "DLF.NS"),
        ("Dabur", "DABUR.NS"), ("Godrej Consumer", "GODREJCP.NS"), ("Godrej Properties", "GODREJPROP.NS"),
        ("ICICI Pru Life", "ICICIPRULI.NS"), ("Indian Hotels", "INDHOTEL.NS"), ("Interglobe", "INDIGO.NS"),
        ("LIC", "LICI.NS"), ("LIC Housing", "LICHSGFIN.NS"), ("Lupin", "LUPIN.NS"),
        ("Marico", "MARICO.NS"), ("Max Healthcare", "MAXHEALTH.NS"), ("Muthoot Finance", "MUTHOOTFIN.NS"),
        ("NHPC", "NHPC.NS"), ("Naukri", "NAUKRI.NS"), ("Oberoi Realty", "OBEROIRLTY.NS"),
        ("PFC", "PFC.NS"), ("PI Industries", "PIIND.NS"), ("Page Industries", "PAGEIND.NS"),
        ("Pidilite", "PIDILITIND.NS"), ("Polycab", "POLYCAB.NS"), ("REC", "RECLTD.NS"),
        ("SRF", "SRF.NS"), ("Siemens", "SIEMENS.NS"), ("Tata Comm.", "TATACOMM.NS"),
        ("Tata Power", "TATAPOWER.NS"), ("Tornt Pharma", "TORNTPHARM.NS"), ("Trent", "TRENT.NS"),
        ("TVS Motor", "TVSMOTOR.NS"), ("United Breweries", "UBL.NS"), ("Vedanta", "VEDL.NS"),
        ("Voltas", "VOLTAS.NS"), ("Zomato", "ZOMATO.NS"),
    ],
    "Nifty Bank": [
        ("HDFC Bank", "HDFCBANK.NS"), ("ICICI Bank", "ICICIBANK.NS"), ("Kotak Bank", "KOTAKBANK.NS"),
        ("Axis Bank", "AXISBANK.NS"), ("SBI", "SBIN.NS"), ("IndusInd Bank", "INDUSINDBK.NS"),
        ("Bank of Baroda", "BANKBARODA.NS"), ("Federal Bank", "FEDERALBNK.NS"),
        ("IDFC First Bank", "IDFCFIRSTB.NS"), ("PNB", "PNB.NS"), ("Bandhan Bank", "BANDHANBNK.NS"),
        ("AU Small Finance", "AUBANK.NS"),
    ],
    "Nifty IT": [
        ("TCS", "TCS.NS"), ("Infosys", "INFY.NS"), ("HCL Tech", "HCLTECH.NS"),
        ("Wipro", "WIPRO.NS"), ("Tech Mahindra", "TECHM.NS"), ("LTIMindtree", "LTIM.NS"),
        ("Mphasis", "MPHASIS.NS"), ("Persistent", "PERSISTENT.NS"), ("Coforge", "COFORGE.NS"),
        ("Oracle Fin", "OFSS.NS"),
    ],
    "Nifty Auto": [
        ("Maruti", "MARUTI.NS"), ("Tata Motors", "TATAMOTORS.NS"), ("M&M", "M&M.NS"),
        ("Bajaj Auto", "BAJAJ-AUTO.NS"), ("Eicher Motors", "EICHERMOT.NS"),
        ("Hero MotoCorp", "HEROMOTOCO.NS"), ("TVS Motor", "TVSMOTOR.NS"),
        ("Ashok Leyland", "ASHOKLEY.NS"), ("Motherson Sumi", "MOTHERSON.NS"),
        ("Balkrishna Ind", "BALKRISIND.NS"), ("MRF", "MRF.NS"), ("Bharat Forge", "BHARATFORG.NS"),
        ("Bosch", "BOSCHLTD.NS"), ("Tube Investments", "TIINDIA.NS"), ("Escorts Kubota", "ESCORTS.NS"),
        ("Sona BLW", "SONACOMS.NS"), ("Samvardhana M.", "SAMVARDH.NS"),
    ],
    "Nifty FMCG": [
        ("HUL", "HINDUNILVR.NS"), ("ITC", "ITC.NS"), ("Nestle", "NESTLEIND.NS"),
        ("Britannia", "BRITANNIA.NS"), ("Dabur", "DABUR.NS"), ("Marico", "MARICO.NS"),
        ("Colgate", "COLPAL.NS"), ("Emami", "EMAMILTD.NS"), ("Godrej Consumer", "GODREJCP.NS"),
        ("Tata Consumer", "TATACONSUM.NS"), ("United Spirits", "MCDOWELL-N.NS"),
        ("Varun Beverages", "VBL.NS"), ("Radico Khaitan", "RADICO.NS"),
        ("Bata India", "BATAINDIA.NS"), ("P&G Hygiene", "PGHH.NS"),
    ],
    "Nifty Pharma": [
        ("Sun Pharma", "SUNPHARMA.NS"), ("Dr Reddy's", "DRREDDY.NS"), ("Cipla", "CIPLA.NS"),
        ("Divis Lab", "DIVISLAB.NS"), ("Lupin", "LUPIN.NS"), ("Aurobindo", "AUROPHARMA.NS"),
        ("Alkem", "ALKEM.NS"), ("Tornt Pharma", "TORNTPHARM.NS"), ("Abbott India", "ABBOTINDIA.NS"),
        ("GSK Pharma", "GLAXO.NS"), ("Pfizer", "PFIZER.NS"), ("IPCA Labs", "IPCALAB.NS"),
        ("Glenmark", "GLENMARK.NS"), ("Granules", "GRANULES.NS"), ("Biocon", "BIOCON.NS"),
        ("Mankind Pharma", "MANKIND.NS"), ("Zydus Lifesciences", "ZYDUSLIFE.NS"),
    ],
    "Nifty Metal": [
        ("Tata Steel", "TATASTEEL.NS"), ("JSW Steel", "JSWSTEEL.NS"), ("Hindalco", "HINDALCO.NS"),
        ("Vedanta", "VEDL.NS"), ("Coal India", "COALINDIA.NS"), ("NMDC", "NMDC.NS"),
        ("SAIL", "SAIL.NS"), ("Jindal Steel", "JINDALSTEL.NS"), ("NALCO", "NATIONALUM.NS"),
        ("MOIL", "MOIL.NS"), ("Welspun Corp", "WELCORP.NS"), ("APL Apollo", "APLAPOLLO.NS"),
        ("Ratnamani Metals", "RATNAMANI.NS"), ("Hindustan Copper", "HINDCOPPER.NS"),
        ("GMDC", "GMDC.NS"),
    ],
    "Nifty Realty": [
        ("DLF", "DLF.NS"), ("Godrej Properties", "GODREJPROP.NS"), ("Oberoi Realty", "OBEROIRLTY.NS"),
        ("Phoenix Mills", "PHOENIXLTD.NS"), ("Prestige Estates", "PRESTIGE.NS"),
        ("Sobha", "SOBHA.NS"), ("Brigade Ent.", "BRIGADE.NS"), ("Mahindra Lifespace", "MAHLIFE.NS"),
        ("Kolte-Patil", "KOLTEPATIL.NS"), ("Sunteck Realty", "SUNTECK.NS"),
        ("Macrotech (Lodha)", "LODHA.NS"), ("Signatureglobal", "SIGNATURE.NS"),
    ],
    "Nifty Energy": [
        ("Reliance", "RELIANCE.NS"), ("ONGC", "ONGC.NS"), ("NTPC", "NTPC.NS"),
        ("Power Grid", "POWERGRID.NS"), ("BPCL", "BPCL.NS"), ("IOC", "IOC.NS"),
        ("GAIL", "GAIL.NS"), ("Tata Power", "TATAPOWER.NS"), ("Adani Green", "ADANIGREEN.NS"),
        ("Adani Total Gas", "ATGL.NS"), ("Oil India", "OIL.NS"), ("HPCL", "HINDPETRO.NS"),
    ],
    "Nifty PSU Bank": [
        ("SBI", "SBIN.NS"), ("PNB", "PNB.NS"), ("Bank of Baroda", "BANKBARODA.NS"),
        ("Canara Bank", "CANBK.NS"), ("Union Bank", "UNIONBANK.NS"), ("Indian Bank", "INDIANB.NS"),
        ("Bank of India", "BANKINDIA.NS"), ("Central Bank", "CENTRALBK.NS"),
        ("Maharashtra Bank", "MAHABANK.NS"), ("IOB", "IOB.NS"), ("UCO Bank", "UCOBANK.NS"),
        ("PSB", "PSB.NS"),
    ],
    "Nifty Fin Service": [
        ("HDFC Bank", "HDFCBANK.NS"), ("ICICI Bank", "ICICIBANK.NS"), ("Kotak Bank", "KOTAKBANK.NS"),
        ("Axis Bank", "AXISBANK.NS"), ("Bajaj Finance", "BAJFINANCE.NS"),
        ("Bajaj Finserv", "BAJAJFINSV.NS"), ("SBI Life", "SBILIFE.NS"), ("HDFC Life", "HDFCLIFE.NS"),
        ("ICICI Lombard", "ICICIGI.NS"), ("ICICI Pru Life", "ICICIPRULI.NS"),
        ("REC", "RECLTD.NS"), ("PFC", "PFC.NS"), ("Muthoot Finance", "MUTHOOTFIN.NS"),
        ("Cholamandalam", "CHOLAFIN.NS"), ("Shriram Finance", "SHRIRAMFIN.NS"),
        ("Jio Financial", "JIOFIN.NS"),
    ],
    "Nifty Infra": [
        ("Adani Ports", "ADANIPORTS.NS"), ("UltraCemco", "ULTRACEMCO.NS"), ("L&T", "LT.NS"),
        ("NTPC", "NTPC.NS"), ("Power Grid", "POWERGRID.NS"), ("GAIL", "GAIL.NS"),
        ("Reliance", "RELIANCE.NS"), ("Coal India", "COALINDIA.NS"), ("DLF", "DLF.NS"),
        ("Bharti Airtel", "BHARTIARTL.NS"), ("Tata Power", "TATAPOWER.NS"),
        ("BHEL", "BHEL.NS"), ("Siemens", "SIEMENS.NS"), ("Thermax", "THERMAX.NS"),
        ("KEC International", "KEC.NS"), ("Kalpataru Power", "KPITTECH.NS"),
    ],
    "Nifty Media": [
        ("Zee Entertainment", "ZEEL.NS"), ("Sun TV", "SUNTV.NS"), ("PVR Inox", "PVRINOX.NS"),
        ("Network18", "NETWORK18.NS"), ("TV18 Broadcast", "TV18BRDCST.NS"),
        ("Saregama", "SAREGAMA.NS"), ("TIPS Music", "TIPSINDLTD.NS"),
        ("Hathway Cable", "HATHWAY.NS"), ("Den Networks", "DEN.NS"),
    ],
    "Nifty CPSE": [
        ("Coal India", "COALINDIA.NS"), ("ONGC", "ONGC.NS"), ("NTPC", "NTPC.NS"),
        ("Power Grid", "POWERGRID.NS"), ("BPCL", "BPCL.NS"), ("IOC", "IOC.NS"),
        ("GAIL", "GAIL.NS"), ("BHEL", "BHEL.NS"), ("NMDC", "NMDC.NS"), ("HAL", "HAL.NS"),
        ("CONCOR", "CONCOR.NS"), ("NBCC", "NBCC.NS"), ("REC", "RECLTD.NS"), ("PFC", "PFC.NS"),
        ("SJVN", "SJVN.NS"), ("IRCTC", "IRCTC.NS"), ("HUDCO", "HUDCO.NS"),
    ],
    "Nifty MNC": [
        ("Abbott India", "ABBOTINDIA.NS"), ("Bosch", "BOSCHLTD.NS"), ("Honeywell Auto", "HONAUT.NS"),
        ("P&G Hygiene", "PGHH.NS"), ("3M India", "3MINDIA.NS"), ("Gillette India", "GILLETTE.NS"),
        ("Pfizer", "PFIZER.NS"), ("GSK Pharma", "GLAXO.NS"), ("Colgate", "COLPAL.NS"),
        ("Siemens", "SIEMENS.NS"), ("ABB India", "ABB.NS"), ("Cummins India", "CUMMINSIND.NS"),
        ("Motherson", "MOTHERSON.NS"), ("Sanofi India", "SANOFI.NS"), ("Nestle", "NESTLEIND.NS"),
        ("Whirlpool", "WHIRLPOOL.NS"), ("Kansai Nerolac", "KANSAINER.NS"),
    ],
    "Nifty Midcap 50": [
        ("Adani Wilmar", "AWL.NS"), ("Angel One", "ANGELONE.NS"), ("Ashok Leyland", "ASHOKLEY.NS"),
        ("Astral", "ASTRAL.NS"), ("BSE", "BSE.NS"), ("Canara Bank", "CANBK.NS"),
        ("Cholamandalam", "CHOLAFIN.NS"), ("Coforge", "COFORGE.NS"), ("Crompton", "CROMPTON.NS"),
        ("Delhivery", "DELHIVERY.NS"), ("Dixon Tech", "DIXON.NS"), ("Exide Ind.", "EXIDEIND.NS"),
        ("Federal Bank", "FEDERALBNK.NS"), ("GNFC", "GNFC.NS"), ("Gujarat Gas", "GUJGASLTD.NS"),
        ("Hindustan Aero.", "HAL.NS"), ("IDFC First", "IDFCFIRSTB.NS"), ("IRFC", "IRFC.NS"),
        ("Jindal Steel", "JINDALSTEL.NS"), ("Jubilant Food", "JUBLFOOD.NS"),
        ("Kalyan Jewellers", "KALYANKJIL.NS"), ("Lupin", "LUPIN.NS"), ("MRF", "MRF.NS"),
        ("Max Healthcare", "MAXHEALTH.NS"), ("Mphasis", "MPHASIS.NS"), ("NMDC", "NMDC.NS"),
        ("Oberoi Realty", "OBEROIRLTY.NS"), ("Oracle Fin", "OFSS.NS"), ("Patanjali Foods", "PATANJALI.NS"),
        ("Persistent", "PERSISTENT.NS"), ("Phoenix Mills", "PHOENIXLTD.NS"), ("PI Industries", "PIIND.NS"),
        ("Polycab", "POLYCAB.NS"), ("REC", "RECLTD.NS"), ("SAIL", "SAIL.NS"),
        ("SRF", "SRF.NS"), ("Shriram Finance", "SHRIRAMFIN.NS"), ("Siemens", "SIEMENS.NS"),
        ("Sundram Fast.", "SUNDRMFAST.NS"), ("TVS Motor", "TVSMOTOR.NS"), ("Tata Comm.", "TATACOMM.NS"),
        ("Tata Power", "TATAPOWER.NS"), ("Tornt Power", "TORNTPOWER.NS"), ("Trent", "TRENT.NS"),
        ("Union Bank", "UNIONBANK.NS"), ("United Spirits", "MCDOWELL-N.NS"), ("Voltas", "VOLTAS.NS"),
        ("Zomato", "ZOMATO.NS"),
    ],
    "Nifty Midcap 150": [
        ("Aarti Ind.", "AARTIIND.NS"), ("Ajanta Pharma", "AJANTPHARM.NS"), ("Alkem", "ALKEM.NS"),
        ("Apcotex Ind.", "APCOTEXIND.NS"), ("Apollo Tyres", "APOLLOTYRE.NS"),
        ("Atul Ltd", "ATUL.NS"), ("Auropharma", "AUROPHARMA.NS"), ("Balkrishna Ind.", "BALKRISIND.NS"),
        ("Bank of India", "BANKINDIA.NS"), ("Bharat Dynamics", "BDL.NS"),
        ("Birla Corp", "BIRLACORPN.NS"), ("Blue Dart", "BLUEDART.NS"), ("Brigade Ent.", "BRIGADE.NS"),
        ("Can Fin Homes", "CANFINHOME.NS"), ("Carborundum", "CARBORUNIV.NS"),
        ("City Union Bank", "CUB.NS"), ("Coromandel Int.", "COROMANDEL.NS"),
        ("DCM Shriram", "DCMSHRIRAM.NS"), ("Deepak Nitrite", "DEEPAKNTR.NS"),
        ("Emami", "EMAMILTD.NS"), ("Endurance Tech.", "ENDURANCE.NS"), ("EPL Ltd", "EPL.NS"),
        ("Equitas SFB", "EQUITASBNK.NS"), ("Escorts Kubota", "ESCORTS.NS"),
        ("Exide Ind.", "EXIDEIND.NS"), ("Fine Organic", "FINEORG.NS"),
        ("Galaxy Surfact.", "GALAXYSURF.NS"), ("Godrej Agrovet", "GODREJAGRO.NS"),
        ("Grindwell Norton", "GRINDWELL.NS"), ("HBL Power", "HBLPOWER.NS"),
        ("HUDCO", "HUDCO.NS"), ("IIFL Finance", "IIFL.NS"), ("IRFC", "IRFC.NS"),
        ("J B Chemicals", "JBCHEPHARM.NS"), ("Jyothy Labs", "JYOTHYLAB.NS"),
        ("KPI Green", "KPIGREEN.NS"), ("Kalyan Jewellers", "KALYANKJIL.NS"),
        ("Karur Vysya", "KARURVYSYA.NS"), ("KPIT Tech", "KPITTECH.NS"), ("L&T Finance", "LTF.NS"),
        ("Laurus Labs", "LAURUSLABS.NS"), ("Mahindra CIE", "MAHINDCIE.NS"),
        ("Minda Industries", "MINDAIND.NS"), ("Narayana Health", "NH.NS"),
        ("NLC India", "NLCINDIA.NS"), ("Praj Industries", "PRAJIND.NS"),
        ("Prince Pipes", "PRINCEPIPE.NS"), ("Radico Khaitan", "RADICO.NS"),
        ("Rajesh Exports", "RAJESHEXPO.NS"), ("Sona BLW", "SONACOMS.NS"),
    ],
}
